### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by afward** [matejdro/plugin.video.nebula#1]
https://choosealicense.com/

**Comment by afward** [comment]
pinging @matejdro

**Comment by matejdro** [comment]
Sorry about that, for some reason I had notifications turned off. You are correct, I should choose one.

**Comment by matejdro** [comment]
https://github.com/matejdro/plugin.video.nebula/commit/59e085f71420ea8e185d6ce8cace26812e12ae7b
